export const SET_ORDER = [
    "OP-01","OP-02","OP-03","OP-04","OP-05","OP-06","OP-07","OP-08",
    "OP-09","OP-10","OP-11","OP-12","OP-13","OP-14","OP-15", "OP-16",
    "OP-17",
    "ST-01","ST-02","ST-03","ST-04","ST-05","ST-06","ST-07","ST-08",
    "ST-09","ST-10","ST-11","ST-12","ST-13","ST-14","ST-15","ST-16",
    "ST-17","ST-18","ST-19","ST-20","ST-21","ST-22","ST-23","ST-24",
    "ST-25","ST-26","ST-27","ST-28","ST-29","ST-30", "ST-31", "ST-32",
    "ST-33","ST-34","ST-35","ST-36","ST-37",
    "EB-01","EB-02","EB-03","EB-04",
    "PRB-01","PRB-02",
  ];
  
export const SET_NAMES: Record<string, string> = {
    "OP-01": "Romance Dawn", "OP-02": "Paramount War", "OP-03": "Pillars of Strength",
    "OP-04": "Kingdoms of Intrigue", "OP-05": "Awakening of the New Era",
    "OP-06": "Wings of the Captain", "OP-07": "500 Years in the Future",
    "OP-08": "Two Legends", "OP-09": "Emperors in the New World",
    "OP-10": "Royal Blood", "OP-11": "A Fist of Divine Speed",
    "OP-12": "Legacy of the Master", "OP-13": "Alliance Rising",
    "OP-14": "The Four Emperors", "OP-15": "Adventure on KAMI's Island",
    "OP-16": "The Time of Battle", "OP-17": "",
    "ST-01": "Straw Hat Crew", "ST-02": "Worst Generation",
    "ST-03": "The Seven Warlords of the Sea", "ST-04": "Animal Kingdom Pirates",
    "ST-05": "One Piece Film Edition", "ST-06": "Absolute Justice",
    "ST-07": "Big Mom Pirates", "ST-08": "Monkey D. Luffy",
    "ST-09": "Yamato", "ST-10": "The Three Captains",
    "ST-11": "Side Uta", "ST-12": "Zoro & Sanji",
    "ST-13": "The Three Brothers' Bond", "ST-14": "3D2Y",
    "ST-15": "Red Edward Newgate", "ST-16": "Green Uta",
    "ST-17": "Blue Donquixote Doflamingo", "ST-18": "Purple Monkey D. Luffy",
    "ST-19": "Black Smoker", "ST-20": "Yellow Charlotte Katakuri",
    "ST-21": "EX · GEAR5", "ST-22": "Ace & Newgate",
    "ST-23": "Red Shanks", "ST-24": "Green Jewelry Bonney",
    "ST-25": "Blue Buggy", "ST-26": "Purple/Black Monkey D. Luffy",
    "ST-27": "Black Marshall D. Teach", "ST-28": "Green/Yellow Yamato",
    "ST-29": "EGGHEAD", "ST-30": "EX · Luffy & Ace",
    "ST-31": "Red Monkey D. Luffy", "ST-32": "Green Roronoa Zoro",
    "ST-33": "Blue Kuzan", "ST-34": "Purple Charlotte Katakuri",
    "ST-35": "Red/Black Sabo", "ST-36": "Yellow Eustass Captain Kid",
    "EB-01": "Memorial Collection", "EB-02": "Anime 25th Collection",
    "EB-03": "Pillars of Strength", "EB-04": "Egghead Crisis",
    "PRB-01": "Premium Booster", "PRB-02": "Premium Booster",
  };
